Add `refine` to public API
rapidsai/cuvs pull request #154
Opened 2024-05-24 17:30 UTC by lowener

Add `cuvs::neighbors::refine` to public API, with it's test

2024-05-24 18:15 UTC, tfeher requested changes
Thanks Mickael for the PR! Looks good, just a few small comments.

2024-05-24 21:45 UTC, cjnolet requested changes
Looks great- just one thing wrt docs (and we should really make sure we're doing it across the public APIs).

2024-05-24 21:45 UTC, cjnolet commented on cpp/include/cuvs/neighbors/refine.hpp
> + */
I know it seems exhaustive and repetitive, but for documentation's sake, please copy and update the docs for each individual prototype below. We want to make sure what any function in the docs a user looks up is going to carry along the full doc string with it, not matter the type.

2024-05-27 09:48 UTC, tfeher approved these changes
Thanks @lowener for the updates, the PR looks good to me!

2024-05-28 18:17 UTC, cjnolet approved these changes

2024-05-28 18:17 UTC, cjnolet commented
/merge

2024-05-28 18:17 UTC, merged