CosineExpanded Distance Metric for CAGRA
rapidsai/cuvs pull request #197
Opened 2024-06-25 13:16 UTC by tarang-jain

2024-09-24 08:17 UTC, achirkin commented on cpp/src/neighbors/detail/cagra/compute_distance.hpp
Hi @tarang-jain, a heads up here: https://github.com/rapidsai/cuvs/pull/296 does a major refactoring of related code; let's have a look together how we can proceed with this PR once you're back to it, ok?
I have similar performance concerns as the ones we discussed on IVF-PQ; maybe it makes sense to keep the dataset normalized for cosine distance (and reuse the inner-product code path)?
Then we can either normalize the query at the time we copy it to the shared memory (pre-processing) or divide by the query norm at the post-processing/filtering step at the end of the kernel.

2025-08-13 11:27 UTC, pmiloslavsky commented
Has this work been abandoned?

2025-08-13 11:41 UTC, cjnolet commented
@pmiloslavsky this PR is currently being reworked to do the computation in place, instead of normalizing the vectors front. The normalization trick works well when users have control over the input vectors, but in the case of CAGRA, the dataset needs to be stored with the graph, and we try not to alter the user’s input on their behalf when we can’t give it right back to them.

2025-08-26 18:00 UTC, tarang-jain commented on cpp/src/neighbors/detail/cagra/compute_distance.hpp
Refactored this PR to do the divide by query norm at the very end (postprocessing stage)-

2025-08-26 18:41 UTC, cjnolet commented on cpp/include/cuvs/neighbors/cagra.hpp
> +  inline void set_dataset_norms(std::optional<raft::device_vector<float, int64_t>>&& norms)
Not a fan of this pattern at all. It would be better if we could instead provide or set these on index creation so that we can make the index itself immutable, rather than having to change ownership of arrays here. We do this in at least 1 other, and i think we need to re-consider that as well.

2025-08-26 21:28 UTC, tarang-jain commented on cpp/include/cuvs/neighbors/cagra.hpp
> +  inline void set_dataset_norms(std::optional<raft::device_vector<float, int64_t>>&& norms)
Removed that helper. Now the index computes and owns the norms directly.

2025-09-15 15:02 UTC, cjnolet commented on cpp/include/cuvs/neighbors/cagra.hpp
> +  void compute_dataset_norms(raft::resources const& res);
I don't think we want this in the public APIs. In general, the index should be very lightweight container for state and all computational functions should be happening as free functions which accept the index object and either use or manipulate its state. This should probably be in the internal APIs if it's not needed in the public APIs.

2025-09-15 15:35 UTC, tarang-jain commented on cpp/include/cuvs/neighbors/cagra.hpp
> +  void compute_dataset_norms(raft::resources const& res);
I'll have to put it into a function, given that it is being used at so many different places. What I could do is make it a private function so that users cannot call it.

2025-09-22 09:59 UTC, tfeher requested changes
Thanks Tarang, the PR looks good overall. Before we merge this, could check the following:
- How large is the binary size increase?
- How much does test time increase?

2025-09-22 09:59 UTC, tfeher commented on cpp/include/cuvs/neighbors/cagra.hpp
> +  std::optional<raft::device_vector<float, int64_t>> dataset_norms_;
This is not saved during serialization. Do I understand correctly, that this will be recomputed when the index is created after loading the data?

2025-09-22 09:59 UTC, tfeher commented on cpp/src/neighbors/cagra.cuh
> +    dataset_norms_ = raft::make_device_vector<float, int64_t>(res, dataset_view.extent(0));
If there is an existing vector, then let's deallocate that first. This could help when we work with very large dataset.
```suggestion
    dataset_norms_ = raft::make_device_vector<float, int64_t>(res, 0);
    dataset_norms_ = raft::make_device_vector<float, int64_t>(res, dataset_view.extent(0));
```

2025-09-22 09:59 UTC, tfeher commented on cpp/tests/neighbors/ann_cagra.cuh
> +          (std::is_same_v<DataT, std::uint8_t> || std::is_same_v<DataT, std::int8_t>)) {
Could you remind me what is the logic behind skipping these tests?

2025-09-22 10:01 UTC, tfeher commented on cpp/tests/neighbors/ann_cagra.cuh
> +          (std::is_same_v<DataT, std::uint8_t> || std::is_same_v<DataT, std::int8_t>)) {
Why does IVF-PQ have this limit? Don't we automatically convert values to float internally?

2025-09-22 17:00 UTC, tarang-jain commented on cpp/include/cuvs/neighbors/cagra.hpp
> +  std::optional<raft::device_vector<float, int64_t>> dataset_norms_;
That is correct! Do we want to save these during serialization?

2025-09-23 22:19 UTC, tarang-jain commented on cpp/tests/neighbors/ann_cagra.cuh
> +          (std::is_same_v<DataT, std::uint8_t> || std::is_same_v<DataT, std::int8_t>)) {
In 2f51b66, I have been able to remove the restriction and support cosine for IVF-PQ with uint8 and int8 inputs. The key was to delay dataset normalization to the point where float conversion has completed and residuals are being computed. This also helps us avoid doing an extra copy of each batch before normalization (this is what we were doing earlier).

2025-09-25 16:23 UTC, tfeher commented on cpp/include/cuvs/neighbors/cagra.hpp
> +  std::optional<raft::device_vector<float, int64_t>> dataset_norms_;
No, just wanted to get confirmation on this.

2025-09-25 18:14 UTC, tfeher reviewed
Thanks @tarang-jain, the PR looks good, I am just waiting for the following questions to be answered before approving.

- How large is the binary size increase?
- How much does test time increase? (It is fine to measure this locally).

2025-09-25 18:14 UTC, tfeher commented on cpp/src/neighbors/ivf_pq/ivf_pq_build.cuh
> +      return raft::cast_op<float>{}(dataset[i]);
While this is correct, a simple `map` would be more natural
```suggestion
    raft::linalg::map(handle, tmp_view, raft::cast_op<float>{}, dataset);
```

2025-09-29 17:40 UTC, tfeher commented on cpp/tests/neighbors/ann_cagra.cuh
> +     cuvs::distance::DistanceType::BitwiseHamming,
I think we do not add more coverage when we test filtering and various distances. I would simply use one of them. 
```suggestion
    {cuvs::distance::DistanceType::L2Expanded},
```

2025-09-29 20:38 UTC, tfeher commented on cpp/tests/neighbors/ann_cagra.cuh
> +     cuvs::distance::DistanceType::CosineExpanded,
Let's skip CosineExpanded for these combinations since we test for various dims elsewhere.

2025-09-29 20:51 UTC, tfeher commented on cpp/tests/neighbors/ann_cagra.cuh
Let's factor out the team_size tensor product.

// Vary graph build algo and merge strategy
```suggestion
inputs2 = raft::util::itertools::product<AnnCagraInputs>(
{100},
{1000},
{64},
{16},
{graph_build_algo::IVF_PQ,
graph_build_algo::NN_DESCENT,
graph_build_algo::ITERATIVE_CAGRA_SEARCH},
{search_algo::AUTO},
{10},
{0},  // team_size
{64},
{1},
    {cuvs::distance::DistanceType::L2Expanded,
     cuvs::distance::DistanceType::InnerProduct,
     cuvs::distance::DistanceType::BitwiseHamming,
     cuvs::distance::DistanceType::CosineExpanded},
{false},
{false},
{0.995},
{std::optional<float>{std::nullopt}},
{std::optional<vpq_params>{std::nullopt}},
{std::optional<bool>{std::nullopt}},
{cuvs::neighbors::MergeStrategy::MERGE_STRATEGY_PHYSICAL,
cuvs::neighbors::MergeStrategy::MERGE_STRATEGY_LOGICAL});
inputs.insert(inputs.end(), inputs2.begin(), inputs2.end());

// Vary team size only.
inputs2 = raft::util::itertools::product<AnnCagraInputs>(
{100},
{1000},
{64},
{16},
graph_build_algo::NN_DESCENT,
},
{10},
{8, 16, 32},  // team_size
{64},
{1},
    {cuvs::distance::DistanceType::L2Expanded,
     cuvs::distance::DistanceType::InnerProduct,
     cuvs::distance::DistanceType::BitwiseHamming,
     cuvs::distance::DistanceType::CosineExpanded},
{false},
{false},
{0.995});
inputs.insert(inputs.end(), inputs2.begin(), inputs2.end());
```

2025-09-29 20:55 UTC, tfeher commented on cpp/tests/neighbors/ann_cagra.cuh
```suggestion
// Fixed dim, and changing neighbors and query size (output matrix size)
auto inputs2 = raft::util::itertools::product<AnnCagraInputs>(
{1, 100},
{1000},
{8},
{1, 16},  // k
{graph_build_algo::NN_DESCENT},
{search_algo::SINGLE_CTA, search_algo::MULTI_CTA, search_algo::MULTI_KERNEL},
{0},  // query size
{0},
{256},
{1},
    {cuvs::distance::DistanceType::L2Expanded},
{false},
{true},
{0.995});
inputs.insert(inputs.end(), inputs2.begin(), inputs2.end());
```
// Additional distances tested with a single search algo.
auto inputs2 = raft::util::itertools::product<AnnCagraInputs>(
{1, 100},
{1000},
{8},
{1, 16},  // k
{graph_build_algo::NN_DESCENT},
{search_algo::SINGLE_CTA},
{0},  // query size
{0},
{256},
{1},
     cuvs::distance::DistanceType::InnerProduct,
     cuvs::distance::DistanceType::BitwiseHamming,
     cuvs::distance::DistanceType::CosineExpanded},
{false},
{true},
{0.995});
inputs.insert(inputs.end(), inputs2.begin(), inputs2.end());

2025-09-29 21:08 UTC, tfeher commented on cpp/tests/neighbors/ann_cagra.cuh
This became (again) a very large tensor product. Lets cut this into smaller parts:


```suggestion
std::vector<AnnCagraInputs> inputs = raft::util::itertools::product<AnnCagraInputs>(
{100},
{1000},
{1, 16},
    {16},                                                      // k
    {graph_build_algo::IVF_PQ, graph_build_algo::NN_DESCENT},  // build algo.
{search_algo::SINGLE_CTA, search_algo::MULTI_CTA, search_algo::MULTI_KERNEL},
{0, 10},  // query size
{0},
{256},
{1},
    {cuvs::distance::DistanceType::L2Expanded,
     cuvs::distance::DistanceType::InnerProduct,
     cuvs::distance::DistanceType::BitwiseHamming,
     cuvs::distance::DistanceType::CosineExpanded},
{false},
{true},
{0.995},
{std::optional<float>{std::nullopt}},
{std::optional<vpq_params>{std::nullopt}},
{std::optional<bool>{std::nullopt}},
{cuvs::neighbors::MergeStrategy::MERGE_STRATEGY_PHYSICAL});

auto inputs2 = raft::util::itertools::product<AnnCagraInputs>({100},
{1000},
{1, 16},
    {16},                                                      // k
   graph_build_algo::NN_DESCENT},  // build algo.
search_algo::MULTI_CTA},
{10},  // query size
{0},
{256},
{1},
    {cuvs::distance::DistanceType::L2Expanded,
     cuvs::distance::DistanceType::InnerProduct,
     cuvs::distance::DistanceType::BitwiseHamming,
     cuvs::distance::DistanceType::CosineExpanded},
{false},
{true},
{0.995},
{std::optional<float>{std::nullopt}},
{std::optional<vpq_params>{std::nullopt}},
{std::optional<bool>{std::nullopt}},
cuvs::neighbors::MergeStrategy::MERGE_STRATEGY_LOGICAL});
  inputs.insert(inputs.end(), inputs2.begin(), inputs2.end());
```

2025-09-30 01:51 UTC, tarang-jain commented
/ok to test a6c6592

2025-09-30 18:09 UTC, tfeher approved these changes
Thanks @tarang-jain for improving the test time. LGTM.

2025-10-02 16:56 UTC, tarang-jain commented
/rerun tests

2025-10-02 16:57 UTC, tarang-jain commented
/rerun failed tests

2025-10-03 18:05 UTC, tarang-jain commented
/merge

2025-10-03 18:10 UTC, merged