Complete Importing of IVF Helpers / Features from RAFT
rapidsai/cuvs pull request #213
Opened 2024-07-05 15:03 UTC by tarang-jain

Utils / Helpers to enable FAISS migration to cuVS from RAFT.

2024-07-22 19:38 UTC, tfeher requested changes
Thanks @tarang-jain for the PR, looks good overall, just few small changes.

2024-07-22 19:38 UTC, tfeher commented on cpp/include/cuvs/neighbors/cagra.hpp
> +   * update the dataset using cuvs::neighbors::cagra::update_dataset. CAGRA does not have `extent`
We do have now `extend`. I would extend the description as 
```suggestion
   * update the dataset using cuvs::neighbors::cagra::update_dataset.
   *
   * Regardless of the value of `attach_dataset_on_build`, the search graph is created using all
   * the vectors in the dataset.  Setting `attach_dataset_on_build = false` can be useful if the 
   * the user needs to build only the search graph but does not intend to search it using CAGRA
   * (e.g. search using another graph search algorithm), or if specific memory placement options 
   * need to be applied on the dataset before it is attached to the index using `update_dataset`.
```

2024-07-22 19:38 UTC, tfeher commented on cpp/include/cuvs/neighbors/cagra.hpp
> + *   In the above example, the dataset is attached to the index and the index is ready for
I think it is sufficient to keep the example in the docstring of `attach_dataset_on_build`.

2024-07-22 19:38 UTC, tfeher commented on cpp/include/cuvs/neighbors/ivf_flat.hpp
> +   * API.
delete

2024-07-22 19:38 UTC, tfeher commented on cpp/src/neighbors/ivf_pq/ivf_pq_list.cuh
> -#pragma once
Why is this removed?

2024-07-22 21:22 UTC, tarang-jain commented
/rerun tests

2024-07-22 21:23 UTC, tarang-jain commented
rerun tests

2024-07-22 22:49 UTC, tarang-jain commented on cpp/src/neighbors/ivf_pq/ivf_pq_list.cuh
> -#pragma once
This header is removed in this PR

2024-07-29 22:28 UTC, tfeher approved these changes
Thanks Tarang for the update, LGTM!

2024-07-30 14:12 UTC, cjnolet commented
/merge

2024-07-30 14:13 UTC, cjnolet approved these changes

2024-07-30 15:03 UTC, tarang-jain commented
/ok to test

2024-07-30 18:38 UTC, merged