WIP: bump nccl floor to 2.18.1.1
rapidsai/cuvs pull request #341
Opened 2024-09-20 21:35 UTC by jameslamb

## Description

Contributes to https://github.com/rapidsai/build-planning/issues/102

Some RAPIDS libraries are using `ncclCommSplit()`, which was introduced in `nccl==2.18.1.1`. This is part of a series of PRs across RAPIDS updating libraries' pins to `nccl>=2.18.1.1` to ensure they get a new-enough version that supports that.

2024-09-24 17:05 UTC, vyasr requested changes
Does cuvs use nccl directly, or only transitively via raft? I notice that it's not specified in the nccl recipes, and if I search the repo I don't see other references which makes me think it's just via raft. If so, we should just drop it here.

2024-09-24 17:55 UTC, jameslamb commented
> Does cuvs use nccl directly, or only transitively via raft? I notice that it's not specified in the nccl recipes, and if I search the repo I don't see other references which makes me think it's just via raft. If so, we should just drop it here.

I searched around and it seems like it's only used transitively through raft.

```shell
git grep -i nccl
```

Looked through the diff of #231 too, and I only see stuff like this:

```cpp
const raft::comms::nccl_clique& clique = handle.get_nccl_clique_handle();
```

2024-09-24 18:23 UTC, vyasr commented
Yeah that matches my expectation. Let's see if tests pass. If they do, please update the title and description accordingly and I can approve.

2024-09-24 19:58 UTC, jameslamb commented
Tests look happy! I've updated the title and description here.

Thanks for the nudge, removing these pins will make the next such update a little easier 😁

2024-09-25 18:27 UTC, jakirkham commented
/merge

2024-09-25 18:27 UTC, merged

2024-09-25 18:27 UTC, jakirkham commented
Thanks all! 🙏