Account for RAFT update
rapidsai/cuvs pull request #454
Opened 2024-11-08 17:25 UTC by viclafargue

NCCL clique initialization function PR in RAFT : https://github.com/rapidsai/raft/pull/2487

Removed instantiation of `raft::comms::build_comms_nccl_only` (https://github.com/rapidsai/raft/issues/2465)

2025-01-07 22:03 UTC, cjnolet commented on cpp/include/cuvs/neighbors/mg.hpp
> +auto build(const raft::device_resources_snmg& clique,
One of the main goals with having the "snmg" resources object match the single-gpu object is that we wanted to be able to remove this additional MG. We should now be able to accept `device_resources` and then check to see if a nccl clique has been set on it (which would imply that it's a multi-gpu resources object and not a single-gpu object). The whole goal with doing this was to consolidate code paths.

2025-01-08 10:14 UTC, viclafargue commented on cpp/include/cuvs/neighbors/mg.hpp
> +auto build(const raft::device_resources_snmg& clique,
The NCCL clique is not set as a resource anymore, but we should still be able to implement the dispatching by checking the dynamic type of the `device_resources`. The real question then is, do we truly want dispatching on both the regular API (`cuvs::neighbors::build`) and the `mg` namespace (`cuvs::neighbors::mg::build`)? It kind of make sense that a user providing a `device_resources_snmg` instance to the regular API (`cuvs::neighbors::build`) would want things to be deployed on multiple GPUs. However, the reverse is not necessarily true. A user who explicitly chose the `mg` namespace, but did not provide the adequate `device_resources_snmg` would fallback to single GPU, potentially unintentionally. Is this what we want?

I propose that we implement the dispatching mechanism solely on the regular API (`cuvs::neighbors::build`) in a dedicated follow-up PR? What do you think?

2025-01-17 00:45 UTC, cjnolet commented
Not sure why CI is still failing. The RAFT PR was merged quite awhile ago but I'm still seeing errors like this:

```
/home/coder/cuvs/cpp/include/cuvs/neighbors/mg.hpp:24:10: fatal error: raft/core/device_resources_snmg.hpp: No such file or directory
     24 | #include <raft/core/device_resources_snmg.hpp>
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2025-01-17 00:46 UTC, bdice commented
This fell back to old 24.12 RAFT packages for unclear reasons:
```
    libraft-headers:             24.12.00-cuda12_241211_geaf9cc72_0 rapidsai   
    libraft-headers-only:        24.12.00-cuda12_241211_geaf9cc72_0 rapidsai   
```
https://github.com/rapidsai/cuvs/actions/runs/12818869804/job/35749392606?pr=454#step:8:521

2025-01-17 00:48 UTC, cjnolet commented
> This fell back to old 24.12 RAFT packages for unclear reasons:

Oh fooey! Thanks for noticing that @bdice, I just realized the darn target branch was never updated!

2025-01-28 01:22 UTC, cjnolet requested changes
I think this is nearly there. Just a couple very minor things at this point. 

Note- cuVS is not header-only and we shouldn't be putting constants in include files (that further couples cuVS to our exact build policies and makes it harder to navigate the build). 

Also, we should not be introducing ANY dependencies in the public header files. That's why we're using raft::resources as a facade so that we don't couple device_resources or device_resources_snmg to our public APIs. In other words, the user can use those objects if they want for convenience, but none of the other APIs in cuVS (nor in RAFT) use those objects because raft::resource is a generic container for these types of objects. That way the user can couple themselves to the dependencie sbut it doesn't force the dependencies on all other users. Does that make sense?

2025-01-28 01:22 UTC, cjnolet commented on cpp/bench/ann/src/cuvs/cuvs_mg_cagra_wrapper.h
> +  raft::device_resources_snmg clique_;
`device_resources_snmg` is a type of `raft::resource`. The pattern here is to accept the `raft::resources` instance and call the free function inside `raft::resource::nccl_resource` underneath to get the clique out of the resource. This way the APIs don't need to look any different.

2025-01-28 01:22 UTC, cjnolet commented on cpp/include/cuvs/neighbors/cagra.hpp
> +auto build(const raft::device_resources_snmg& clique,
Please don't couple the standard headers to nccl. This is no good. Instead, please just accept a `raft::device_resources` here but provide a function in `raft::resource::nccl_resource` namespace to introspect the resources for a nccl clique (otherwise fail). The snmg build params should be anough of a difference

2025-01-28 01:22 UTC, cjnolet commented on cpp/src/neighbors/mg/mg_cagra_float_uint32_t.cu
> +  cuvs::neighbors::mg::index<cagra::index<T, IdxT>, T, IdxT> distribute<T, IdxT>(                  \
I thought we were removing the mg namespace completely from the public APIs.

2025-04-01 22:56 UTC, cjnolet commented on cpp/CMakeLists.txt
> -        src/neighbors/mg/nccl_comm.cpp
Nice to see this removed.

2025-04-01 23:07 UTC, cjnolet commented on cpp/bench/ann/src/cuvs/cuvs_mg_cagra_wrapper.h
> +  raft::device_resources_snmg clique_;
We should be able to store `raft::resources` here now, right? The idea being that `has_resource_factory` for the `NCCL_CLIQUE` will be `true` when it's an SNMG type? (else, we'll need to add some other type of state, along with an accessor in the `resources/nccl_clique.hpp` for `is_multi_gpu()` and `is_multi_node()`

2025-04-01 23:11 UTC, cjnolet commented on cpp/bench/ann/src/cuvs/cuvs_mg_cagra_wrapper.h
> +  raft::device_resources_snmg clique_;
Maybe it's not a huge deal since this file is specific to mg. Could we at least rename the file to `snmg`, though? (Just in case we end up adding an mnmg then we won't have a clash).

2025-04-01 23:12 UTC, cjnolet commented on cpp/include/cuvs/neighbors/common.hpp
> +  const raft::resources& handle,
Very nice!

2025-04-01 23:13 UTC, cjnolet commented on cpp/include/cuvs/neighbors/common.hpp
> +namespace cuvs::neighbors {
Why restart/redefine the namespace here? Can't we just extend the existing namespace?

2025-04-01 23:22 UTC, cjnolet commented on cpp/tests/neighbors/mg.cuh
> -#include <cuvs/neighbors/mg.hpp>
Can we rename this to `snmg.cuh` (and the corresponding namespace to `snmg`)?

2025-04-22 22:27 UTC, cjnolet commented
/ok to test

2025-04-22 22:27 UTC, cjnolet approved these changes

2025-04-22 22:29 UTC, KyleFromNVIDIA approved these changes

2025-04-22 22:35 UTC, cjnolet commented
/ok to test

2025-04-22 22:37 UTC, cjnolet commented
/ok to test da48376

2025-04-22 22:37 UTC, cjnolet commented
/merge

2025-04-23 03:58 UTC, cjnolet commented
/ok to test da48

2025-04-23 03:59 UTC, cjnolet commented
/ok to test da48376

2025-04-23 04:00 UTC, divyegala commented
/ok to test d2e2be9

2025-04-23 04:32 UTC, divyegala commented
/merge

2025-04-23 11:39 UTC, viclafargue commented
/ok to test

2025-04-23 11:42 UTC, achirkin commented
/ok to test

2025-04-23 11:44 UTC, viclafargue commented
/ok to test https://github.com/rapidsai/cuvs/pull/454/commits/1e1d97e83e1595a77a726021b4b1265778720080

2025-04-23 11:49 UTC, achirkin commented
/ok to test 1e1d97e

2025-04-23 15:34 UTC, cjnolet commented
/ok to test 34d67ee

2025-04-23 20:53 UTC, cjnolet commented
/merge

2025-04-23 21:21 UTC, merged